# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PaperlessNgxUploader < Formula
  desc "Example rust release."
  homepage "https://github.com/oliverziegert/homebrew-tap"
  version "0.0.15"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oliverziegert/homebrew-tap/releases/download/0.0.15/paperless-ngx-uploader_Darwin_x86_64.tar.gz"
      sha256 "6a483e55761c6284f938a0322c0c03580060046a1a839d10fc91b1f56e23a443"

      def install
        bin.install "paperless-ngx-uploader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oliverziegert/homebrew-tap/releases/download/0.0.15/paperless-ngx-uploader_Darwin_arm64.tar.gz"
      sha256 "2bb9e5e55f999a466cc5c1c338111110f413b58185c150a9190751ebf0d8a659"

      def install
        bin.install "paperless-ngx-uploader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oliverziegert/homebrew-tap/releases/download/0.0.15/paperless-ngx-uploader_Linux_x86_64.tar.gz"
        sha256 "cd6af37e781da996537b3d1ece0348186eb22f7426819135c76b6ff9dba27fb8"

        def install
          bin.install "paperless-ngx-uploader"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oliverziegert/homebrew-tap/releases/download/0.0.15/paperless-ngx-uploader_Linux_arm64.tar.gz"
        sha256 "166592ab178f349992967dccd3531c6c01e01511d45db4b40eed936c1ee99b16"

        def install
          bin.install "paperless-ngx-uploader"
        end
      end
    end
  end
end
