# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PaperlessNgxUploader < Formula
  desc "Example rust release."
  homepage "https://github.com/oliverziegert/homebrew-tap"
  version "0.1.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oliverziegert/homebrew-tap/releases/download/0.1.0/paperless-ngx-uploader_Darwin_x86_64.tar.gz"
      sha256 "6a19d183075e446fdc54998ee8b08f17b8b6c37962552addb0ffa6557a7c2438"

      def install
        bin.install "paperless-ngx-uploader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oliverziegert/homebrew-tap/releases/download/0.1.0/paperless-ngx-uploader_Darwin_arm64.tar.gz"
      sha256 "686b9b24a331b9ada83e336a519508e48ed11dbe7d1ffbdccf8f4402a687bc8f"

      def install
        bin.install "paperless-ngx-uploader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oliverziegert/homebrew-tap/releases/download/0.1.0/paperless-ngx-uploader_Linux_x86_64.tar.gz"
        sha256 "ff021819dd6eebc4d07b545ea146e8749a5802a5d9cb19d83720d51c7355ce65"

        def install
          bin.install "paperless-ngx-uploader"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oliverziegert/homebrew-tap/releases/download/0.1.0/paperless-ngx-uploader_Linux_arm64.tar.gz"
        sha256 "7728c75928b4bae3dcd8813f24384e712cf6da7e042d10e4afd33d8669715209"

        def install
          bin.install "paperless-ngx-uploader"
        end
      end
    end
  end
end
